name: Build and Release for musl

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true  # Load the image locally instead of pushing
          tags: local-build:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract built executable
        run: |
          mkdir -p ./dist
          container_id=$(docker create local-build:latest)
          docker cp $container_id:/app/dist/. ./dist/
          docker rm $container_id
          cd dist
          tar czf ../TwitchDropsMiner-linux-musl.tar.gz .

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: TwitchDropsMiner-linux

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: TwitchDropsMiner-linux-musl.tar.gz
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true