name: sync-fork-and-tags
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: { }
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      workflows: write
    steps:
      - name: Check out your repo
        uses: actions/checkout@v4
      - name: Add upstream remote
        run: git remote add upstream https://github.com/Windows200000/TwitchDropsMiner-updated.git
      - name: Sync branch with upstream
        run: gh repo sync "$REPOSITORY" -b "$BRANCH_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
      - name: Fetch all tags from upstream
        run: git fetch upstream --tags
      - name: Push tags to origin
        run: git push origin --tags --force
