name: sync-fork-and-add-tag
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: { }
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Sync fork and possibly tag
        run: |
          # Capture the current HEAD commit
          prev_head=$(git rev-parse HEAD)
          
          # Get the newest tag from the repository
          NEWEST_TAG=$(curl -s https://api.github.com/repos/fireph/TwitchDropsMiner-Alpine/releases/latest | grep -oP '(?<="tag_name": ")[^"]*')
          
          # Sync the fork
          gh repo sync "$REPOSITORY" -b "$BRANCH_NAME"
          
          # Capture the new HEAD commit
          new_head=$(git rev-parse HEAD)
          
          # If the new HEAD is different than the old HEAD, tag and push
          if [ "$prev_head" != "$new_head" ]; then
            version_number="${NEWEST_TAG#v}"
            next_tag="v$((version_number + 1))"
            git tag "$next_tag"
            git push origin --tags
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
